openapi: 3.0.1
info:
  version: 0.10.7
  title: NextGen CommissionPro
  description: API para genrenciar as vendas da empresa.
servers:
  - url: htp://localhost:5000/v1
tags:
  - name: auth
    description: Rotas de Authentication
  - name: user
    description: Rotas do Usuário
  

paths:
  /auth/login:
    post:
      tags: 
        - auth
      summary: login sistema
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              required: 
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              example:
                email: email@email.com
                password: password1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  user: 
                    $ref: '#/components/schemas/User'
                  tokens:
                    $ref: '#/components/schemas/AuthTokens'
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                statusCode: 401
                message: Invalid email or password
  /auth/logout:
    post:
      tags:
        - auth
      summary: logout do sistema
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
              example: 
                refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJhYzUzNDk1NGI1NDEzOTgwNmMxMTIiLCJpYXQiOjE1ODkyOTg0ODQsImV4cCI6MTU4OTMwMDI4NH0.m1U63blB0MLej_WfB7yC2FTMnCziif9X8yzwDEfJXAg
      responses:
        '204':
          description: No content
        '404':
          $ref: '#/components/responses/NotFound'
  
  /auth/refresh-tokens:
    post:
      tags:
        - auth
      summary: atualizar os tokens
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
              example: 
                refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJhYzUzNDk1NGI1NDEzOTgwNmMxMTIiLCJpYXQiOjE1ODkyOTg0ODQsImV4cCI6MTU4OTMwMDI4NH0.m1U63blB0MLej_WfB7yC2FTMnCziif9X8yzwDEfJXAg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokens'
      
        '401':
          $ref: '#/components/responses/Unauthorized'
              
        
  /auth/forgot-password:
    post:
      tags:
        - auth
      summary: esqueceu senha
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
               - email
               - redirect
              properties:
                email:
                  type: string
                  format: email
                redirect:
                  type: string
                  format: redirect
              example:
                email: email@email.com
                redirect: link enviado pelo front
      responses:
        '204':
          description: NO content
        '404':
          $ref: '#/components/responses/NotFound'
        
  /auth/reset-forgot-password:
    post:
      tags:
       - auth
      summary: trocar de senha
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Deve ser passado um token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
               - password
              properties:
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: Deve conter números e letras
              example:
                password: password12
      responses:
        '201':
          description: NO content
        '401':
          description: Troca de senha falhou
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Troca de senha falhou
          
  /auth/reset-current-password:
    post:
      tags:
       - auth
      summary: trocar senha atual
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Deve ser passado um token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
               - password
              properties:
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: Deve conter números e letras
              example:
                password: password12
      responses:
        '201':
          description: NO content
        '401':
          description: Troca de senha falhou
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Troca de senha falhou
                
  /users:
    post:
      tags:
        - user
      summary: Criar usuário
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                data:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - email
                      - password
                      - role
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                        description: Deve ser único
                      password:
                        type: string
                        format: password
                        minLength: 8
                        description: Deve conter pelo menos uma letra e um número
                      role:
                        type: string
                        enum: 
                          - ADMIN
                          - VENDEDOR
                          - GERENTE_VENDAS
                  example:
                    - name: "fake name"
                      email: "fake@example.com"
                      password: "password1"
                      role: "VENDEDOR"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '400':
          $ref: '#/components/responses/DuplicatedEmail'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
    get:
      tags:
        - user
      summary: Listar todos usuários
      description: Apenas admin tem acesso a lista de usuários
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: role
          schema:
            type: string
          description: Role do usuário
        - in: query
          name: sortBy
          schema:
            type: string
          description: Organizar a consulta pelo nome do usuário
        - in: query
          name: sortType
          schema: 
            type: string
          description: Organizar a consulta por asc ou desc
        - in: query
          name: limit
          schema: 
            type: integer
          description: Número máximo de usuários
        - in: query
          name: page
          schema: 
            type: integer
          description: O número da página
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 10
                  totalPages:
                    type: integer
                    example: 1
                  totalResults:
                    type: integer
                    example: 1
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  
  /users/{id}:
    get:
      tags: 
        - user
      summary: Busca usuário pelo id
      description: Usuários logados tem acesso apenas suas informações. Apenas admins conseguem buscar outros usuários.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Id do usuário
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
        - user
      summary: Atualizar usuário
      description: Usuários logados tem acesso apenas suas informações. Apenas admins conseguem atualizar outros usuários.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Id do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                data:
                  type: object
                  required:
                    - name
                    - email
                    - role
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                      description: Deve ser único
                    role:
                      type: string
                      enum: 
                        - ADMIN
                        - VENDEDOR
                        - GERENTE_VENDAS
                    password:
                      type: string
                      format: password
                      minLength: 8
                      description: Deve conter pelo menos uma letra e um número
                    bloqueado:
                      type: boolean
                      format: bloqueado
                  example:
                    name: "fake name"
                    email: "fake@example.com"
                    role: "VENDEDOR"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'          
            

              

components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Vinicius
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        role:
          type: string
          enum: [ADMIN, VENDEDOR, GERENTE_VENDAS]
        bloqueado: 
          type: boolean
          format: bloqueado
        ativo:
          type: boolean
          format: ativo
      example:
        id: 550e8400-e29b-41d4-a716-446655440000
        email: fake@example.com
        name: fake name
        role: VENDEDOR
        
    Token:
      type: object
      properties:
        token:
          type: string
        expires:
          type: string
          format: date-time
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJhYzUzNDk1NGI1NDEzOTgwNmMxMTIiLCJpYXQiOjE1ODkyOTg0ODQsImV4cCI6MTU4OTMwMDI4NH0.m1U63blB0MLej_WfB7yC2FTMnCziif9X8yzwDEfJXAg
      
    AuthTokens:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/Token'
        refresh:
          $ref: '#/components/schemas/Token'
    Error:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
          
    
          
  responses:
      DuplicatedEmail:
        description: Email already taken
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
            examples:
              example:
                value:
                  code: 400
                  message: Email already taken
      Unauthorized:
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
            examples:
              example:
                value:
                  code: 401
                  message: Please authenticate
      Forbidden:
        description: Forbidden
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
            examples:
              example:
                value:
                  code: 403
                  message: Forbidden
      NotFound:
        description: Not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
            examples:
              example:
                value:
                  code: 404
                  message: Not found

  